// This file is autogenerated by lib/css-plugin.js
export const app: string;
export const drop: string;
export const optionPair: string;
export const horizontal: string;
export const vertical: string;
export const appLoader: string;