// This file is autogenerated by lib/css-plugin.js
export const input: string;
export const thumb: string;
export const thumbWrapper: string;
export const valueDisplay: string;
export const touchActive: string;