// This file is autogenerated by lib/css-plugin.js
export const range: string;
export const labelText: string;
export const rangeWcContainer: string;
export const rangeWc: string;
export const textInput: string;