// This file is autogenerated by lib/css-plugin.js
export const output: string;
export const altBackground: string;
export const twoUp: string;
export const pinchZoom: string;
export const pinchTarget: string;
export const controls: string;
export const buttonGroup: string;
export const button: string;
export const zoom: string;
export const active: string;
export const firstButton: string;
export const lastButton: string;
export const zoomValue: string;
export const buttonsNoWrap: string;
export const pixelated: string;