// This file is autogenerated by lib/css-plugin.js
export const checkbox: string;
export const track: string;
export const thumb: string;
export const thumbTrack: string;
export const realCheckbox: string;