// This file is autogenerated by lib/css-plugin.js
export const checkbox: string;
export const realCheckbox: string;
export const icon: string;
export const checked: string;
export const disabled: string;