export interface FeatureItem {
  id: number;
  name: string;
  category: string;
  description: string;
  badge: string;
}

export const CATEGORIES = [
  'All Features',
  'Compression & Optimization',
  'Format Conversion',
  'Resize & Dimension Tools',
  'Image Editing',
  'AI Features',
  'Metadata & Security',
  'Ecommerce & Seller',
  'SEO & Developer',
  'Productivity & Pro',
  'Analytics & Quality',
  'Color & Background',
  'Advanced & Creative',
];

export const FEATURES_DATA: FeatureItem[] = [
  // 1. Compression & Optimization
  { id: 1, category: 'Compression & Optimization', name: 'Lossless Compression', description: 'Compress images without losing quality using WebP, PNG, or AVIF lossless settings.', badge: 'WASM Optimized' },
  { id: 2, category: 'Compression & Optimization', name: 'Smart Compression', description: 'Automatic quality adjustments based on structural similarity (SSIM) to maximize bytes saved.', badge: 'AI/SSIM' },
  { id: 3, category: 'Compression & Optimization', name: 'Custom Quality Compression', description: 'Precise control over quantization tables, smoothing coefficients, and quality factors.', badge: 'WASM Option' },
  { id: 4, category: 'Compression & Optimization', name: 'Bulk Image Compression', description: 'Process multiple images simultaneously in your browser queue.', badge: 'Batch Support' },
  { id: 5, category: 'Compression & Optimization', name: 'Folder Compression', description: 'Import and compress entire directories keeping directory structure intact.', badge: 'Native File System' },
  { id: 6, category: 'Compression & Optimization', name: 'Progressive JPEG Optimization', description: 'Multi-pass progressive scans for faster page rendering on slow network connections.', badge: 'MozJPEG Core' },
  { id: 7, category: 'Compression & Optimization', name: 'PNG Optimization', description: 'Advanced color palette reduction and interlace pass configurations.', badge: 'OxiPNG Core' },
  { id: 8, category: 'Compression & Optimization', name: 'GIF Optimization', description: 'Frame optimization, delay adjustment, and color dithering controls.', badge: 'WASM Engine' },
  { id: 9, category: 'Compression & Optimization', name: 'SVG Optimization', description: 'Path simplification, metadata stripping, and XML minification.', badge: 'Clean Vector' },
  { id: 10, category: 'Compression & Optimization', name: 'AVIF Optimization', description: 'Next-generation AV1 coding for exceptional compression efficiency at high quality.', badge: 'AVIF Core' },

  // 2. Format Conversion
  { id: 11, category: 'Format Conversion', name: 'JPG to PNG', description: 'Convert lossy JPEGs into transparent lossless PNG format with alpha channel addition.', badge: 'Converter' },
  { id: 12, category: 'Format Conversion', name: 'PNG to JPG', description: 'Convert transparent PNGs into standard JPEGs with custom background color replacement.', badge: 'Converter' },
  { id: 13, category: 'Format Conversion', name: 'JPG to WEBP', description: 'Upgrade JPEGs to modern WebP format for up to 30% smaller file sizes.', badge: 'WASM WebP' },
  { id: 14, category: 'Format Conversion', name: 'WEBP to JPG', description: 'Export WebP assets to widely compatible JPEG format for legacy system support.', badge: 'Converter' },
  { id: 15, category: 'Format Conversion', name: 'PNG to WEBP', description: 'Convert PNGs to WebP while fully preserving alpha channel transparency.', badge: 'WASM WebP' },
  { id: 16, category: 'Format Conversion', name: 'WEBP to PNG', description: 'Decode WebP images back into lossless 24-bit PNG files.', badge: 'Converter' },
  { id: 17, category: 'Format Conversion', name: 'JPG to AVIF', description: 'Convert JPEGs to AVIF to leverage advanced HDR and wide color gamut support.', badge: 'AVIF WASM' },
  { id: 18, category: 'Format Conversion', name: 'AVIF to JPG', description: 'Down-convert AVIF files to JPEG for older devices and legacy web engines.', badge: 'Converter' },
  { id: 19, category: 'Format Conversion', name: 'HEIC to JPG', description: 'Decode Apple HEIC/HEIF camera photos into standard JPEG files.', badge: 'Apple Decoder' },
  { id: 20, category: 'Format Conversion', name: 'TIFF Converter', description: 'Convert large multi-page TIFF document scans to lightweight web formats.', badge: 'TIFF Decoder' },

  // 3. Resize & Dimension Tools
  { id: 21, category: 'Resize & Dimension Tools', name: 'Smart Resize', description: 'Downscale images using high-quality lanczos3 or bilinear resampling filters.', badge: 'Resampler' },
  { id: 22, category: 'Resize & Dimension Tools', name: 'Bulk Resize', description: 'Resize entire batches of images to identical dimensions in a single click.', badge: 'Batch Resize' },
  { id: 23, category: 'Resize & Dimension Tools', name: 'Percentage Resize', description: 'Quickly scale dimensions by 25%, 50%, 75%, or custom percentage factors.', badge: 'Fast Presets' },
  { id: 24, category: 'Resize & Dimension Tools', name: 'Fixed Dimension Resize', description: 'Crop or stretch images to fit exact width and height pixel boundaries.', badge: 'Geometry' },
  { id: 25, category: 'Resize & Dimension Tools', name: 'Aspect Ratio Lock', description: 'Constrain scaling to prevent stretching or skewing the image geometry.', badge: 'Constraint' },
  { id: 26, category: 'Resize & Dimension Tools', name: 'Social Media Resize Presets', description: 'One-click dimensions for Instagram, Facebook, Twitter, LinkedIn, and YouTube covers.', badge: 'Presets' },
  { id: 27, category: 'Resize & Dimension Tools', name: 'Ecommerce Resize Presets', description: 'Auto-scale to match Amazon, Flipkart, Shopify, and Etsy product image guidelines.', badge: 'Ecommerce' },
  { id: 28, category: 'Resize & Dimension Tools', name: 'Thumbnail Generator', description: 'Automatically generate 150x150 or 200x200 crop previews.', badge: 'Quick Crop' },
  { id: 29, category: 'Resize & Dimension Tools', name: 'Batch Dimension Editor', description: 'Change dimensions across a wide processing queue.', badge: 'Batch Action' },
  { id: 30, category: 'Resize & Dimension Tools', name: 'DPI Changer', description: 'Modify metadata DPI/PPI density headers without altering pixel dimensions.', badge: 'EXIF Edit' },

  // 4. Image Editing
  { id: 31, category: 'Image Editing', name: 'Crop Tool', description: 'Crop pixels using precise box coordinate sliders or freeform handles.', badge: 'Focal Editor' },
  { id: 32, category: 'Image Editing', name: 'Smart Crop', description: 'Auto-detection of image focal points to keep key subjects centered when cropping.', badge: 'Saliency Crop' },
  { id: 33, category: 'Image Editing', name: 'Rotate', description: 'Turn images 90°, 180°, 270°, or any angle.', badge: 'Rotate' },
  { id: 34, category: 'Image Editing', name: 'Flip Horizontal', description: 'Mirror the canvas horizontally for layout symmetry.', badge: 'Transform' },
  { id: 35, category: 'Image Editing', name: 'Flip Vertical', description: 'Flip the canvas upside down.', badge: 'Transform' },
  { id: 36, category: 'Image Editing', name: 'Border Generator', description: 'Wrap images with customizable border widths and HEX colors.', badge: 'Canvas FX' },
  { id: 37, category: 'Image Editing', name: 'Rounded Corner Generator', description: 'Apply smooth border radius curves to image borders.', badge: 'Canvas FX' },
  { id: 38, category: 'Image Editing', name: 'Add Background Color', description: 'Inject custom solid backdrops behind transparent PNG/WebP files.', badge: 'Alpha Inject' },
  { id: 39, category: 'Image Editing', name: 'Canvas Resize', description: 'Expand or shrink the bounding box area around your image.', badge: 'Padding' },
  { id: 40, category: 'Image Editing', name: 'Image Merge', description: 'Overlay or combine multiple images into a single layout.', badge: 'Collage Engine' },

  // 5. AI Features
  { id: 41, category: 'AI Features', name: 'AI Background Removal', description: 'Client-side segmentation model to extract subjects and remove backgrounds instantly.', badge: 'In-Browser AI' },
  { id: 42, category: 'AI Features', name: 'AI Object Removal', description: 'Smart in-painting brush to clean up blemishes, dust, or unwanted objects.', badge: 'In-Browser AI' },
  { id: 43, category: 'AI Features', name: 'AI Image Enhancement', description: 'Automatically adjust contrast, white balance, and exposure dynamically.', badge: 'Auto Balance' },
  { id: 44, category: 'AI Features', name: 'AI Upscaler', description: 'Super-resolution network to double or quadruple image detail without blurriness.', badge: 'AI Super-Res' },
  { id: 45, category: 'AI Features', name: 'AI Face Enhancement', description: 'Specialized details restoration for portraits and selfies.', badge: 'Portrait AI' },
  { id: 46, category: 'AI Features', name: 'AI Noise Reduction', description: 'Denoise camera sensor grain while keeping edge definitions clean.', badge: 'Denoise' },
  { id: 47, category: 'AI Features', name: 'AI Sharpening', description: 'Correct out-of-focus blurs using deconvolution-inspired neural filters.', badge: 'De-Blur' },
  { id: 48, category: 'AI Features', name: 'AI Color Correction', description: 'Neural color matching to balance tones.', badge: 'Color Match' },
  { id: 49, category: 'AI Features', name: 'AI Old Photo Restoration', description: 'Repair cracks, scratches, and fade damage from scanned historical images.', badge: 'Restorer' },
  { id: 50, category: 'AI Features', name: 'AI Product Image Enhancement', description: 'Brighten, shadow-correct, and highlight commercial product shots.', badge: 'Ecom AI' },

  // 6. Metadata & Security
  { id: 51, category: 'Metadata & Security', name: 'EXIF Viewer', description: 'Read embedded EXIF, IPTC, and XMP camera details.', badge: 'EXIF Core' },
  { id: 52, category: 'Metadata & Security', name: 'EXIF Remover', description: 'Remove sensitive camera metadata with one click.', badge: 'Privacy Guard' },
  { id: 53, category: 'Metadata & Security', name: 'Metadata Cleaner', description: 'Thoroughly strip all software footprints, timestamps, and thumbnails.', badge: 'Privacy Guard' },
  { id: 54, category: 'Metadata & Security', name: 'GPS Data Remover', description: 'Erase latitude, longitude, and elevation coordinates from camera photos.', badge: 'GPS Wipe' },
  { id: 55, category: 'Metadata & Security', name: 'Copyright Metadata Editor', description: 'Insert custom author, copyright, and business signature strings.', badge: 'EXIF Writer' },
  { id: 56, category: 'Metadata & Security', name: 'Watermark Adder', description: 'Overlay custom text or logos with color, opacity, and positioning controls.', badge: 'Watermark' },
  { id: 57, category: 'Metadata & Security', name: 'Watermark Remover (User-Owned Images)', description: 'Clean up self-owned watermarks from catalog images.', badge: 'Eraser' },
  { id: 58, category: 'Metadata & Security', name: 'Image Encryption Download', description: 'Password-protect or encrypt file downloads for secure transfers.', badge: 'Encrypted' },
  { id: 59, category: 'Metadata & Security', name: 'Secure Temporary Storage', description: 'Client-side IndexedDB storage ensuring no files are sent to any cloud server.', badge: 'IndexedDB Secure' },
  { id: 60, category: 'Metadata & Security', name: 'Auto File Expiry', description: 'Instant local cache expiration upon tab closure for enterprise security.', badge: 'Auto-Expiring' },

  // 7. Ecommerce & Seller
  { id: 61, category: 'Ecommerce & Seller', name: 'Amazon Image Checker', description: 'Verify if images meet Amazon\'s strict 1000px+ pure white background rules.', badge: 'Amazon Spec' },
  { id: 62, category: 'Ecommerce & Seller', name: 'Flipkart Image Checker', description: 'Ensure assets match Flipkart listing size and quality policies.', badge: 'Flipkart Spec' },
  { id: 63, category: 'Ecommerce & Seller', name: 'Meesho Image Checker', description: 'Check aspect ratio and crop layouts for Meesho catalog templates.', badge: 'Meesho Spec' },
  { id: 64, category: 'Ecommerce & Seller', name: 'Etsy Image Checker', description: 'Validate Etsy\'s recommended photo aspect ratios and lighting.', badge: 'Etsy Spec' },
  { id: 65, category: 'Ecommerce & Seller', name: 'Shopify Image Checker', description: 'Optimization audit for Shopify storefront speed and display compliance.', badge: 'Shopify Spec' },
  { id: 66, category: 'Ecommerce & Seller', name: 'Product Background White Generator', description: 'Force transparent spaces to pure white (#FFFFFF) for marketplace standards.', badge: 'Ecom standard' },
  { id: 67, category: 'Ecommerce & Seller', name: 'Product Shadow Generator', description: 'Generate realistic drop or contact shadows beneath product subjects.', badge: 'Shadow Render' },
  { id: 68, category: 'Ecommerce & Seller', name: 'Product Reflection Generator', description: 'Apply professional mirror reflection effects below commercial items.', badge: 'Mirror FX' },
  { id: 69, category: 'Ecommerce & Seller', name: 'Lifestyle Mockup Generator', description: 'Embed product images into lifestyle mockups.', badge: 'Collage Core' },
  { id: 70, category: 'Ecommerce & Seller', name: 'Product Collage Generator', description: 'Grid together multiple angles of a product for detail galleries.', badge: 'Collage Core' },

  // 8. SEO & Developer
  { id: 71, category: 'SEO & Developer', name: 'Image SEO Analyzer', description: 'Detailed report on filename structure, file size weight, and format recommendations.', badge: 'SEO Audit' },
  { id: 72, category: 'SEO & Developer', name: 'Alt Text Generator', description: 'Smart context analyzer to suggest descriptive SEO alt tags.', badge: 'Metadata SEO' },
  { id: 73, category: 'SEO & Developer', name: 'Filename Optimizer', description: 'Rewrite filenames replacing spaces with hyphens and removing junk characters.', badge: 'Slug Core' },
  { id: 74, category: 'SEO & Developer', name: 'Structured Data Image Generator', description: 'Produce Schema.org JSON-LD scripts for your images.', badge: 'SEO JSON-LD' },
  { id: 75, category: 'SEO & Developer', name: 'OpenGraph Image Creator', description: 'Generate OG images for social sharing.', badge: 'OpenGraph' },
  { id: 76, category: 'SEO & Developer', name: 'Pinterest Image Generator', description: 'Crop and format tall images optimized for Pinterest grids.', badge: 'Pinterest Layout' },
  { id: 77, category: 'SEO & Developer', name: 'Social Share Preview Tool', description: 'Live rendering simulator of how images appear on WhatsApp, Twitter, and Facebook.', badge: 'Social Previews' },
  { id: 78, category: 'SEO & Developer', name: 'Image Sitemap Generator', description: 'Generate XML sitemap nodes for Google Image Search discovery.', badge: 'Sitemap XML' },
  { id: 79, category: 'SEO & Developer', name: 'Web Performance Analyzer', description: 'Calculate PageSpeed impact and load speed estimations.', badge: 'PageSpeed' },
  { id: 80, category: 'SEO & Developer', name: 'Image Accessibility Checker', description: 'Analyze contrast ratios and colorblind visibility scores.', badge: 'A11y Audit' },

  // 9. Productivity & Pro
  { id: 81, category: 'Productivity & Pro', name: 'Drag & Drop Upload', description: 'Upload single or multiple files by dragging them straight onto the viewport.', badge: 'DND Upload' },
  { id: 82, category: 'Productivity & Pro', name: 'Multi Upload', description: 'Select multiple files from your system storage in one batch.', badge: 'Batch Upload' },
  { id: 83, category: 'Productivity & Pro', name: 'Bulk Processing', description: 'Run transformations across many files concurrently.', badge: 'Multi-Threaded' },
  { id: 84, category: 'Productivity & Pro', name: 'ZIP Download', description: 'Pack all compressed assets into a single ZIP archive locally.', badge: 'Zip Pack' },
  { id: 85, category: 'Productivity & Pro', name: 'Before/After Comparison', description: 'Draggable comparison slider to view raw and compressed outputs side-by-side.', badge: 'Compare Slider' },
  { id: 86, category: 'Productivity & Pro', name: 'Side-by-Side Viewer', description: 'Split screen layouts for comparative pixel inspections.', badge: 'Dual View' },
  { id: 87, category: 'Productivity & Pro', name: 'Processing Queue', description: 'Visual status tracker for pending, active, and completed files.', badge: 'Queue Manager' },
  { id: 88, category: 'Productivity & Pro', name: 'Download History', description: 'Session logs detailing files optimized and total storage bytes saved.', badge: 'Savings Log' },
  { id: 89, category: 'Productivity & Pro', name: 'Saved Presets', description: 'Save your custom configuration rules for fast workflow repetitions.', badge: 'User Presets' },
  { id: 90, category: 'Productivity & Pro', name: 'Cloud Storage Integration', description: 'Connect directly to Google Drive or Dropbox for importing assets.', badge: 'Cloud Import' },

  // 10. Analytics & Quality
  { id: 91, category: 'Analytics & Quality', name: 'Compression Savings Calculator', description: 'Live tracker showing exact bytes saved per image.', badge: 'Live Analytics' },
  { id: 92, category: 'Analytics & Quality', name: 'Website Speed Impact Calculator', description: 'Estimate bandwidth savings and page speed improvements.', badge: 'Bandwidth Savvy' },
  { id: 93, category: 'Analytics & Quality', name: 'Image Quality Analyzer', description: 'Calculate PSNR (Peak Signal-to-Noise Ratio) and SSIM values.', badge: 'Image Quality' },
  { id: 94, category: 'Analytics & Quality', name: 'Resolution Analyzer', description: 'Details aspect ratio, color depth, and print size dimensions.', badge: 'Aspect/DPI' },
  { id: 95, category: 'Analytics & Quality', name: 'Color Profile Analyzer', description: 'Identify color spaces (sRGB, Adobe RGB, Display P3).', badge: 'ICC Profiles' },
  { id: 96, category: 'Analytics & Quality', name: 'Transparency Detector', description: 'Instantly check for the presence of alpha/transparency channels.', badge: 'Alpha Check' },
  { id: 97, category: 'Analytics & Quality', name: 'Duplicate Image Detector', description: 'Scan for duplicate files loaded into the processing queue.', badge: 'Asset Audit' },
  { id: 98, category: 'Analytics & Quality', name: 'Similar Image Finder', description: 'Find images with identical visual content at different resolutions.', badge: 'Asset Audit' },
  { id: 99, category: 'Analytics & Quality', name: 'Largest Asset Detector', description: 'Identify the heaviest assets in your batch list to focus optimization.', badge: 'Asset Audit' },
  { id: 100, category: 'Analytics & Quality', name: 'Performance Score Report', description: 'Comprehensive audit score based on industry web performance standards.', badge: 'Performance Card' },

  // 11. Color & Background
  { id: 101, category: 'Color & Background', name: 'Color Palette Extractor', description: 'Generate a coordinated color scheme palette based on pixel data.', badge: 'Palette Tool' },
  { id: 102, category: 'Color & Background', name: 'Dominant Color Detector', description: 'Detect the dominant colors that define the visual theme.', badge: 'Palette Tool' },
  { id: 103, category: 'Color & Background', name: 'Brand Color Extractor', description: 'Extract key marketing and branding tones directly from layout assets.', badge: 'Palette Tool' },
  { id: 104, category: 'Color & Background', name: 'Gradient Generator', description: 'Create beautiful linear and radial CSS/Image gradients visually.', badge: 'Gradient' },
  { id: 105, category: 'Color & Background', name: 'Color Blindness Preview', description: 'Simulate Deuteranopia, Protanopia, and Tritanopia colorspaces in real-time.', badge: 'Simulator' },
  { id: 106, category: 'Color & Background', name: 'Contrast Ratio Checker', description: 'Measure luminance contrast differences between elements.', badge: 'A11y checker' },
  { id: 107, category: 'Color & Background', name: 'Color Harmony Generator', description: 'Calculate complementary, monochromatic, and analogous color sets.', badge: 'Harmony' },
  { id: 108, category: 'Color & Background', name: 'RGB to HEX Converter', description: 'Convert RGB channel numbers to web HEX code strings.', badge: 'Utility' },
  { id: 109, category: 'Color & Background', name: 'HEX to RGB Converter', description: 'Convert HEX code strings back to numerical RGB values.', badge: 'Utility' },
  { id: 110, category: 'Color & Background', name: 'CMYK Converter', description: 'Map RGB monitor pixels to CMYK percentages for print.', badge: 'Utility' },

  // 12. Background Tools (grouped in Color & Background)
  { id: 111, category: 'Color & Background', name: 'Transparent Background Creator', description: 'Wipe solid backdrops to render transparent alpha layouts.', badge: 'Alpha Layer' },
  { id: 112, category: 'Color & Background', name: 'Solid Color Background Generator', description: 'Fill alpha regions with custom solid colors instantly.', badge: 'Canvas Color' },
  { id: 113, category: 'Color & Background', name: 'Gradient Background Generator', description: 'Draw dynamic multi-color linear gradients under transparent assets.', badge: 'Canvas Color' },
  { id: 114, category: 'Color & Background', name: 'Blur Background Tool', description: 'Apply smooth gaussian blur backdrops behind portrait cutouts.', badge: 'Blur FX' },
  { id: 115, category: 'Color & Background', name: 'Pattern Background Generator', description: 'Fill canvas spaces with repeating geometric checker, dot, or grid patterns.', badge: 'Canvas Pattern' },
  { id: 116, category: 'Color & Background', name: 'Studio Background Creator', description: 'Replicate professional photography studio lighting vignettes.', badge: 'Studio Vignette' },
  { id: 117, category: 'Color & Background', name: 'Shadow Background Generator', description: 'Draw soft cast shadows onto canvas backdrops for depth.', badge: 'Depth FX' },
  { id: 118, category: 'Color & Background', name: 'White Background Generator', description: 'Inject clean #FFFFFF space behind products for e-commerce listings.', badge: 'Ecom White' },
  { id: 119, category: 'Color & Background', name: 'Black Background Generator', description: 'Inject deep #000000 backdrop space for dramatic product galleries.', badge: 'Ecom Black' },
  { id: 120, category: 'Color & Background', name: 'Background Color Replacer', description: 'Swap specific background color ranges dynamically.', badge: 'Chroma Range' },

  // 13. Batch Processing (grouped under Productivity & Pro)
  { id: 121, category: 'Productivity & Pro', name: 'Batch Rename Images', description: 'Rename files in your queue utilizing dynamic templates.', badge: 'Batch Rename' },
  { id: 122, category: 'Productivity & Pro', name: 'Batch Watermark', description: 'Overlay copyright branding text or logos across multiple files in a batch.', badge: 'Batch Watermark' },
  { id: 123, category: 'Productivity & Pro', name: 'Batch Format Conversion', description: 'Translate collections of files into AVIF, WebP, JPG, or PNG together.', badge: 'Batch Convert' },
  { id: 124, category: 'Productivity & Pro', name: 'Batch Crop', description: 'Apply unified crop parameters across multiple target images.', badge: 'Batch Crop' },
  { id: 125, category: 'Productivity & Pro', name: 'Batch Rotate', description: 'Rotate entire asset folders 90°, 180°, or 270° degrees in unison.', badge: 'Batch Transform' },
  { id: 126, category: 'Productivity & Pro', name: 'Batch DPI Change', description: 'Set print metadata density parameters across a large queue.', badge: 'Batch EXIF' },
  { id: 127, category: 'Productivity & Pro', name: 'Batch Border Addition', description: 'Apply branded borders to lists of items in one pass.', badge: 'Batch FX' },
  { id: 128, category: 'Productivity & Pro', name: 'Batch Background Change', description: 'Inject solid backdrops across a multi-file selection.', badge: 'Batch Background' },
  { id: 129, category: 'Productivity & Pro', name: 'Batch Thumbnail Generation', description: 'Generate matching thumbnail sizes across many loaded files.', badge: 'Batch Resize' },
  { id: 130, category: 'Productivity & Pro', name: 'Batch Metadata Removal', description: 'Strip EXIF metadata blocks across all files for complete privacy.', badge: 'Batch Security' },

  // 14. Image Analysis (grouped under Analytics & Quality)
  { id: 131, category: 'Analytics & Quality', name: 'Blur Detection', description: 'Perform frequency analysis to detect blurry images.', badge: 'Quality Engine' },
  { id: 132, category: 'Analytics & Quality', name: 'Sharpness Score Checker', description: 'Calculate a numeric sharpness value using edge gradient scores.', badge: 'Quality Engine' },
  { id: 133, category: 'Analytics & Quality', name: 'Brightness Analyzer', description: 'Audit average canvas luminance levels for clipping.', badge: 'Quality Engine' },
  { id: 134, category: 'Analytics & Quality', name: 'Contrast Analyzer', description: 'Measure brightness distribution and contrast ranges.', badge: 'Quality Engine' },
  { id: 135, category: 'Analytics & Quality', name: 'Noise Analyzer', description: 'Detect high-frequency noise levels and compression artifacts.', badge: 'Quality Engine' },
  { id: 136, category: 'Analytics & Quality', name: 'Exposure Analyzer', description: 'Identify overexposed highlights and underexposed shadow spots.', badge: 'Quality Engine' },
  { id: 137, category: 'Analytics & Quality', name: 'Image Quality Score', description: 'Composite score evaluating focus, exposure, and compression.', badge: 'Quality Report' },
  { id: 138, category: 'Analytics & Quality', name: 'Compression Quality Score', description: 'Estimate quality loss ratio compared to original input.', badge: 'Quality Report' },
  { id: 139, category: 'Analytics & Quality', name: 'Duplicate Image Checker', description: 'Identify duplicated files via client-side hash calculations.', badge: 'Queue Scan' },
  { id: 140, category: 'Analytics & Quality', name: 'Similar Image Detector', description: 'Locate close visual content matches through downsampled comparisons.', badge: 'Queue Scan' },

  // 15. Ecommerce Seller Tools (grouped under Ecommerce & Seller)
  { id: 141, category: 'Ecommerce & Seller', name: 'Product Image Dimension Checker', description: 'Validate if sizes conform to marketplace recommendations.', badge: 'Market Audit' },
  { id: 142, category: 'Ecommerce & Seller', name: 'Marketplace Compliance Checker', description: 'Audit background white ratio, file size, and aspect ratios.', badge: 'Market Audit' },
  { id: 143, category: 'Ecommerce & Seller', name: 'Product Collage Maker', description: 'Combine product angles into professional multi-image collages.', badge: 'Mockup Builder' },
  { id: 144, category: 'Ecommerce & Seller', name: 'Multi-Angle Product Layout Creator', description: 'Grid together front, side, and detail shots cleanly.', badge: 'Mockup Builder' },
  { id: 145, category: 'Ecommerce & Seller', name: 'Product Sheet Generator', description: 'Overlay specifications and dimensions directly onto images.', badge: 'Listing Sheet' },
  { id: 146, category: 'Ecommerce & Seller', name: 'Product Catalog Image Generator', description: 'Generate optimized uniform catalog listing shots.', badge: 'Catalog Core' },
  { id: 147, category: 'Ecommerce & Seller', name: 'Offer Banner Generator', description: 'Add promotional banners and sale stickers onto listing headers.', badge: 'Banner Core' },
  { id: 148, category: 'Ecommerce & Seller', name: 'Sale Sticker Generator', description: 'Overlay Sale, % Off, and New Arrival stickers.', badge: 'Banner Core' },
  { id: 149, category: 'Ecommerce & Seller', name: 'Product Label Generator', description: 'Format printable barcodes and specifications labels.', badge: 'Label Creator' },
  { id: 150, category: 'Ecommerce & Seller', name: 'Product Size Guide Creator', description: 'Construct visual height/width comparison scale vectors.', badge: 'Listing Sheet' },

  // 16. Social Media Tools (grouped under Resize & Dimension Tools)
  { id: 151, category: 'Resize & Dimension Tools', name: 'Instagram Post Creator', description: 'Crop and scale to square 1080x1080 or portrait 1080x1350 bounds.', badge: 'Social Crop' },
  { id: 152, category: 'Resize & Dimension Tools', name: 'Instagram Story Resizer', description: 'Resize instantly to 1080x1920 portrait dimensions.', badge: 'Social Crop' },
  { id: 153, category: 'Resize & Dimension Tools', name: 'Facebook Cover Creator', description: 'Fit cover art into 820x312 desktop bounds.', badge: 'Social Crop' },
  { id: 154, category: 'Resize & Dimension Tools', name: 'LinkedIn Banner Creator', description: 'Resize background banners to 1584x396 parameters.', badge: 'Social Crop' },
  { id: 155, category: 'Resize & Dimension Tools', name: 'YouTube Thumbnail Creator', description: 'Resize graphics to standard 1280x720 16:9 thumbnails.', badge: 'Social Crop' },
  { id: 156, category: 'Resize & Dimension Tools', name: 'Twitter Header Creator', description: 'Fit profiles to exact 1500x500 header banners.', badge: 'Social Crop' },
  { id: 157, category: 'Resize & Dimension Tools', name: 'Pinterest Pin Creator', description: 'Optimize vertical aspect ratios to 2:3 (e.g. 1000x1500).', badge: 'Social Crop' },
  { id: 158, category: 'Resize & Dimension Tools', name: 'WhatsApp Status Resizer', description: 'Export vertical 1080x1920 layout posts.', badge: 'Social Crop' },
  { id: 159, category: 'Resize & Dimension Tools', name: 'Social Media Safe Area Checker', description: 'Overlay avatar and button safe-zones to prevent layout overlaps.', badge: 'Social Safe' },
  { id: 160, category: 'Resize & Dimension Tools', name: 'Thumbnail CTR Optimizer', description: 'Analyze focal details and contrast levels to maximize visual impact.', badge: 'Social CTR' },

  // 17. Watermark & Branding (grouped under Metadata & Security)
  { id: 161, category: 'Metadata & Security', name: 'Text Watermark Generator', description: 'Add customized copyright or brand name text headers across your images.', badge: 'Branding Tool' },
  { id: 162, category: 'Metadata & Security', name: 'Logo Watermark Generator', description: 'Overlay transparent logo PNG files as signature marks.', badge: 'Branding Tool' },
  { id: 163, category: 'Metadata & Security', name: 'Tile Watermark Generator', description: 'Repeat watermark grids diagonally to prevent cropping modifications.', badge: 'Tiled Shield' },
  { id: 164, category: 'Metadata & Security', name: 'Diagonal Watermark Tool', description: 'Overlay single diagonal copyright barriers across images.', badge: 'Barriers' },
  { id: 165, category: 'Metadata & Security', name: 'Copyright Stamp Generator', description: 'Inject visual copyright text metadata logs.', badge: 'Legal Stamp' },
  { id: 166, category: 'Metadata & Security', name: 'QR Watermark Generator', description: 'Inject QR codes linking to business domains directly onto images.', badge: 'QR Overlay' },
  { id: 167, category: 'Metadata & Security', name: 'Signature Watermark Tool', description: 'Digitize and overlay custom signature paths onto graphics.', badge: 'Signature' },
  { id: 168, category: 'Metadata & Security', name: 'Batch Brand Overlay', description: 'Overlay logos and watermarks across many assets concurrently.', badge: 'Batch Brand' },
  { id: 169, category: 'Metadata & Security', name: 'Brand Preset Manager', description: 'Save logo assets and styling templates for repeating tasks.', badge: 'Brand presets' },
  { id: 170, category: 'Metadata & Security', name: 'Watermark Opacity Controller', description: 'Fine-tune transparent blending levels via sliders.', badge: 'Blend FX' },

  // 18. Advanced Editing (grouped under Image Editing)
  { id: 171, category: 'Image Editing', name: 'Perspective Correction', description: 'Adjust perspective angles to straighten distorted architecture shots.', badge: 'Perspective' },
  { id: 172, category: 'Image Editing', name: 'Lens Distortion Correction', description: 'Fix wide-angle camera lens curves.', badge: 'Distortion Fix' },
  { id: 173, category: 'Image Editing', name: 'Barrel Distortion Fix', description: 'Remove fisheye barrel distortion anomalies.', badge: 'Distortion Fix' },
  { id: 174, category: 'Image Editing', name: 'Keystone Correction', description: 'Align vertical and horizontal lines of skewed scans.', badge: 'Keystone' },
  { id: 175, category: 'Image Editing', name: 'Auto Straighten', description: 'Detect horizons and auto-rotate canvas to align horizontally.', badge: 'Auto Alignment' },
  { id: 176, category: 'Image Editing', name: 'Horizon Alignment', description: 'Manual rotation sliders to level skewed horizons.', badge: 'Alignment' },
  { id: 177, category: 'Image Editing', name: 'Grid Crop Tool', description: 'Overlay guide grids during crop adjustments.', badge: 'Focal Editor' },
  { id: 178, category: 'Image Editing', name: 'Rule of Thirds Overlay', description: 'Compose photos matching standard rules.', badge: 'Rule of Thirds' },
  { id: 179, category: 'Image Editing', name: 'Focus Area Crop', description: 'Crop tightly around key image details.', badge: 'Focal Crop' },
  { id: 180, category: 'Image Editing', name: 'Auto Center Subject', description: 'Scan borders and center elements on the canvas background.', badge: 'Subject Centering' },

  // 19. Advanced & Creative (Creative Tools)
  { id: 181, category: 'Advanced & Creative', name: 'Meme Generator', description: 'Overlay top and bottom captions in bold impact font styles.', badge: 'Meme Core' },
  { id: 182, category: 'Advanced & Creative', name: 'Quote Image Generator', description: 'Format typography quotes with backdrops.', badge: 'Quote Core' },
  { id: 183, category: 'Advanced & Creative', name: 'Poster Creator', description: 'Construct high-impact marketing poster layouts.', badge: 'Marketing Core' },
  { id: 184, category: 'Advanced & Creative', name: 'Flyer Creator', description: 'Generate web promotional flyers from templates.', badge: 'Marketing Core' },
  { id: 185, category: 'Advanced & Creative', name: 'Certificate Generator', description: 'Format and export print-ready certificates.', badge: 'Template Core' },
  { id: 186, category: 'Advanced & Creative', name: 'Badge Generator', description: 'Create vector-wrapped visual badges for websites.', badge: 'Badge Core' },
  { id: 187, category: 'Advanced & Creative', name: 'Sticker Generator', description: 'Add die-cut white outline borders to convert photos to stickers.', badge: 'Sticker Core' },
  { id: 188, category: 'Advanced & Creative', name: 'Profile Frame Creator', description: 'Layer circular frames over avatars.', badge: 'Profile Frame' },
  { id: 189, category: 'Advanced & Creative', name: 'Avatar Creator', description: 'Crop and filter images into avatars.', badge: 'Profile Frame' },
  { id: 190, category: 'Advanced & Creative', name: 'Thumbnail Template Builder', description: 'Save thumbnail layouts for recurring uploads.', badge: 'Presets builder' },

  // 20. Advanced & Creative (Utility Tools)
  { id: 191, category: 'Advanced & Creative', name: 'Image Splitter', description: 'Slice large images into equal grids.', badge: 'Splitter Core' },
  { id: 192, category: 'Advanced & Creative', name: 'Image Joiner', description: 'Merge multiple images vertically or horizontally.', badge: 'Merger Core' },
  { id: 193, category: 'Advanced & Creative', name: 'Image Grid Maker', description: 'Arrange pictures into customized grid boards.', badge: 'Merger Core' },
  { id: 194, category: 'Advanced & Creative', name: 'Contact Sheet Generator', description: 'Generate rows of thumbnails for fast catalogs.', badge: 'Contact Sheet' },
  { id: 195, category: 'Advanced & Creative', name: 'Screenshot Beautifier', description: 'Apply mock background gradients and shadows to screenshots.', badge: 'Beautifier' },
  { id: 196, category: 'Advanced & Creative', name: 'Device Mockup Generator', description: 'Overlay viewport captures onto mobile or laptop designs.', badge: 'Mockups' },
  { id: 197, category: 'Advanced & Creative', name: 'Browser Frame Generator', description: 'Wrap graphic layouts inside clean browser window frames.', badge: 'Mockups' },
  { id: 198, category: 'Advanced & Creative', name: 'Polaroid Effect Tool', description: 'Format pictures with vintage borders and handwriting.', badge: 'Filters FX' },
  { id: 199, category: 'Advanced & Creative', name: 'Reflection Effect Generator', description: 'Render realistic ground mirror reflections underneath objects.', badge: 'Filters FX' },
  { id: 200, category: 'Advanced & Creative', name: 'Drop Shadow Generator', description: 'Draw adjustable blurry shadows around transparent PNGs.', badge: 'Depth FX' },

  // 21. SEO & Developer (Dev & SEO Tools)
  { id: 201, category: 'SEO & Developer', name: 'Responsive Image Generator', description: 'Export images in 320px, 640px, 768px, 1024px, and 1280px widths.', badge: 'Responsive' },
  { id: 202, category: 'SEO & Developer', name: 'Srcset Generator', description: 'Generate responsive HTML code snippets.', badge: 'HTML Srcset' },
  { id: 203, category: 'SEO & Developer', name: 'Lazy Loading Preview', description: 'Verify image layouts behavior during lazy rendering.', badge: 'Performance' },
  { id: 204, category: 'SEO & Developer', name: 'OpenGraph Image Generator', description: 'Export custom scaled 1.91:1 social media share cards.', badge: 'OG Metadata' },
  { id: 205, category: 'SEO & Developer', name: 'Twitter Card Image Generator', description: 'Export Twitter summary large image format graphics.', badge: 'OG Metadata' },
  { id: 206, category: 'SEO & Developer', name: 'Blog Featured Image Creator', description: 'Format cover graphics with title typography.', badge: 'Cover Creator' },
  { id: 207, category: 'SEO & Developer', name: 'Image Sitemap Builder', description: 'Generate sitemap XML markup.', badge: 'XML Sitemap' },
  { id: 208, category: 'SEO & Developer', name: 'Image CDN URL Generator', description: 'Generate paths optimized for image delivery networks.', badge: 'CDN Setup' },
  { id: 209, category: 'SEO & Developer', name: 'HTML Image Tag Generator', description: 'Generate image tags containing explicit width, height, and alt.', badge: 'HTML code' },
  { id: 210, category: 'SEO & Developer', name: 'Alt Text Suggestion Tool', description: 'Suggest alt descriptors based on image categories.', badge: 'SEO Alt' },

  // 22. SEO & Developer (Accessibility Tools)
  { id: 211, category: 'SEO & Developer', name: 'Alt Text Validator', description: 'Inspect alt attributes for length, keyword stuffings, and structure.', badge: 'A11y Audit' },
  { id: 212, category: 'SEO & Developer', name: 'Contrast Compliance Checker', description: 'Verify WCAG compliance grades (AA/AAA) for overlay texts.', badge: 'A11y Audit' },
  { id: 213, category: 'SEO & Developer', name: 'Readability Preview', description: 'Simulate legibility settings across widths.', badge: 'Legibility' },
  { id: 214, category: 'SEO & Developer', name: 'Vision Impairment Simulator', description: 'Simulate blurred sight, cataract, and colorblindness.', badge: 'A11y View' },
  { id: 215, category: 'SEO & Developer', name: 'Low Vision Preview', description: 'Render high contrast overlays to assist design reviews.', badge: 'A11y View' },
  { id: 216, category: 'SEO & Developer', name: 'Screen Reader Image Tester', description: 'Audit image attribute structures for aria-label descriptors.', badge: 'A11y Tester' },
  { id: 217, category: 'SEO & Developer', name: 'Accessibility Score Generator', description: 'Provide overall WCAG checklist ratings.', badge: 'A11y Score' },
  { id: 218, category: 'SEO & Developer', name: 'Accessible Thumbnail Checker', description: 'Verify contrast on small scale elements.', badge: 'A11y Score' },
  { id: 219, category: 'SEO & Developer', name: 'Color Accessibility Analyzer', description: 'Scan color schemes for colorblind limitations.', badge: 'Color A11y' },
  { id: 220, category: 'SEO & Developer', name: 'WCAG Image Compliance Checker', description: 'Verify WCAG 2.2 guideline standards.', badge: 'WCAG Audit' },

  // 23. Productivity & Pro (Professional Features)
  { id: 221, category: 'Productivity & Pro', name: 'Undo/Redo History', description: 'Step back and forth through editing adjustments without restarting.', badge: 'State Engine' },
  { id: 222, category: 'Productivity & Pro', name: 'Processing History', description: 'Review details of optimized files during current browser sessions.', badge: 'Session Log' },
  { id: 223, category: 'Productivity & Pro', name: 'Recent Files', description: 'Quickly reload recently processed items.', badge: 'Session Log' },
  { id: 224, category: 'Productivity & Pro', name: 'Favorite Presets', description: 'Flag custom configurations for fast profile loadings.', badge: 'Favorite' },
  { id: 225, category: 'Productivity & Pro', name: 'Workspace Saving', description: 'Preserve loaded items and parameters inside local storage.', badge: 'Storage Save' },
  { id: 226, category: 'Productivity & Pro', name: 'Auto Save', description: 'Automatically sync edits to state to prevent accidental tab data losses.', badge: 'Auto Save' },
  { id: 227, category: 'Productivity & Pro', name: 'Download Manager', description: 'Review queue progress, download items individually.', badge: 'Manager' },
  { id: 228, category: 'Productivity & Pro', name: 'Project Templates', description: 'Load predefined layouts and format presets for workflows.', badge: 'Presets' },
  { id: 229, category: 'Productivity & Pro', name: 'Export Profiles', description: 'Set standard export settings profiles (e.g. Ecom-White, Social-Post).', badge: 'Presets' },
  { id: 230, category: 'Productivity & Pro', name: 'Performance Dashboard', description: 'Detailed charts auditing compression ratios and network loading impacts.', badge: 'Performance' },
];
