// This file is autogenerated by lib/css-plugin.js
export const compress: string;
export const options: string;
export const options1Theme: string;
export const options2Theme: string;
export const options1: string;
export const options2: string;
export const multiPanel: string;
export const back: string;
export const backBlob: string;
export const strokePulse: string;
export const backX: string;